// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tiakuneprywurazjmtqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpYWt1bmVwcnl3dXJhemptdHF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNzYxNjUsImV4cCI6MjA1OTk1MjE2NX0.KyPNAiN9vxJzLy06REtLZ47rw5gLUzigWFPTPqWF14A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);